### ISSUE TITLE
Questions about Model training

### ISSUE THREAD

**Issue by fromSun2Moon** [yekeren/VCR-pretraining#1]
Hi, Keren.I'm trying to run b2t2 code. I have some questions.

my command here. python -m modeling.trainer_main --model_dir=bert_dir --pipeline_proto=../configs/b2t2_test.pbtxt
I get the error "no module bert_vcr.modeling". I could not find the bert_vcr folder (I think here is vcr modeling with bert and frcnn modeling, am I right?)Could I ask the bert_vcr folder and modeling file please?I hope to hear from you.
Thanks.

**Comment by yekeren** [comment]
Sorry for the late response. I recently graduated and was working on relocation to another city. The folder of `bert_vcr` is the modified [bert implementation](https://github.com/google-research/bert). Please see my modification in [HERE](https://github.com/yekeren/bert/tree/yekeren/bert). In the `modeling.py`, I added a tag feature. See the changes [HERE](https://github.com/yekeren/bert/commit/fbdaea3baa70c63c8e8e07df3acc3d400aae65aa)
